apiVersion: v1
kind: Service
metadata:
  name: transaction-api
  labels:
    app.kubernetes.io/name: transaction-api
spec:
  selector:
    app.kubernetes.io/name: transaction-api
  ports:
    - port: 8080
      targetPort: 8080
